### ISSUE TITLE
Specialized "Documents" service must be PersistedDocuments

### ISSUE THREAD

**Issue by alvaro9210** [CarbonLDP/carbonldp-js-sdk#110]
The specialized services  like `Users`, `Roles`, etc. behavior basically has `PersistedDocuments`,
thus this classes must be changed to documents.

For this, there should be possible to register existing document, with its URI.

Changes in the `Users` and `Roles` elements, will be tracked in their respective issues: #185, #186 respectively.

## Previous issue content:

Currently the SDK doesn't have a way to list the existing agents of an app.
It would be great for the SDK to let users have such method.
We should add two methods:
 - .list()
    To list, as pointers, the existing agents.
 - .getAll()
    To get, as agents, the existing agents.

**Comment by roddolf** [comment]
This services shares almost the same basic methods as the PersistedDocument elements.

Making them persisted documents would be the best options, adding specialized methods by decorating them.
