### ISSUE TITLE
Add flexibility to set the enabled property of an Agent while creating it

### ISSUE THREAD

**Issue by alvaro9210** [CarbonLDP/carbonldp-js-sdk#123]
It would be nice if we could provide a way to allow the Agents' registering process to indicate that the Agent being persisted is being registered enabled or disabled.
I am thinking of two possible ways:
 - Extend the `Agent interface` to include the `enabled` property (which is currently only in `PersistedAgent.Class`)
 - Provide a third optional parameter to `Agents.register` method, it could be an optional parameter called disabled, which if present, the Agent will be created with the `enabled` property set to `false`, if not, the agent will be created with the `enabled` property set to `true`, which is the actual behavior.

**Comment by MiguelAraCo** [comment]
This won't be added to the current version but it may be good to leave it open to make sure it is taken care off on the next one.

**Comment by MiguelAraCo** [comment]
Focus has shifted to the new version and this issue in particular won't be ported.
