### ISSUE TITLE
Modify SDK to match new platform's structure

### ISSUE THREAD

**Issue by roddolf** [CarbonLDP/carbonldp-js-sdk#141]
Modify SDK to match new platform's structure:
- Will be a unique context: Carbon
- getAPIDescription name will change to:
    - getPlatformDescription / getPlatformInfo / getPlatformMetadata
    - getInstanceDescription / getInstanceInfo / getInstanceMetadata
- App related modules will be removed
- Agent related modules will be rename to User
- Credentials:
  - Old Credentials will be renamed
  - A new Credentials will be added
- Platform related modules will be removed

**Comment by MiguelAraCo** [comment]
We may need to split this issue into sub-issues to be able to track progress more effectively.
