### ISSUE TITLE
Refactor "Class" convention and use full names for exported elements

### ISSUE THREAD

**Issue by alvaro9210** [CarbonLDP/carbonldp-js-sdk#161]
When compiling an App using the SDK and said App has any errors regarding a mismatch among the types, the SDK is not clear to which types it's referring to.
Here's and example:
![pasted image at 2017_09_14 03_14 pm](https://user-images.githubusercontent.com/4240006/30454038-86640708-9960-11e7-8e48-5f0949f39dd8.png)

This gives developers a hard time to figure out of which types the compiler is complaining of.

**Comment by roddolf** [comment]
The list of names changes are:

## `carbonldp`

- AbstractContext
  - `Class` => `AbstractContext`
- AccessPoint
  - `RDF_CLASS` => `AccessPoint.TYPE`
  - `DocumentClass` => `AccessPoint`
  - `Class` => `AccessPointBase`
  - `Factory` => `AccessPoint`
- BlankNode
  - `Class` => `BlankNode`
  - `Factory` => `BlankNode`
- Carbon
  - `Class` => `Carbon`
- Context
  - `Class` => `Context`
- Document
  - `RDF_CLASS` => `Document.TYPE`
  - `SCHEMA` => `Document.SCHEMA`
  - `Class` => `Document`
  - `Factory` => `Document`
- Documents
  - `Class` => `Documents`
- Errors [Removed]
- Fragment
  - `Class` => `Fragment`
  - `Factory` => `Fragment`
- FreeResources
  - `Class` => `FreeResources`
  - `Factory` => `FreeResources`
- HTTP [Removed]
- JSONLD [Removed]
- LDP [Removed]
- NamedFragment
  - `Class` => `NamedFragment`
  - `Factory` => `NamedFragment`
- NS [Removed]
- ObjectSchema
  - `PropertyDefinition` => `ObjectSchemaProperty`
  - `Class` => `ObjectSchema`
  - `ContainerType`
  - `PointerType`
  - `DigestedPropertyDefinition` => `DigestedObjectSchemaProperty`
  - `DigestedObjectSchema`
  - `Resolver` => `ObjectSchemaResolver`
  - `Digester` => `ObjectSchemaDigester` (Similar to a Util class)
  - `Util` => `ObjectSchemaUtils`
- PersistedAccessPoint
  - `Class` => `PersistedAccessPoint`
- PersistedBlankNode
  - `Class` => `PersistedBlankNode`
- PersistedDocument
  - `Class` => `PersistedDocument`
  - `Factory` => `PersisteDocument`
- PersistedFragment
  - `Class` => `PersistedFragment`
  - `Factory` => `PersistedFragment`
- PersistedNamedFragment
  - `Class` => `PersistedNamedFragment`
  - `Factory` => `PersistedNamedFragment`
- PersistedProtectedDocument
  - `Class` => `PersistedProtectedDocument`
  - `Factory` => `PersistedProtectedDocument`
- PersistedResource
  - `Class` => `PersistedResource`
  - `Factory` => `PersistedResource`
- Pointer
  - `Class` => `Pointer`
  - `Library` => `PointerLibrary`
  - `Factory` => `Pointer`
  - `Util` => `Pointer`
  - `Validator` => `PointerValidator`
- ProtectedDocument
  - `RDF_CLASS` => `ProtectedDocument.TYPE`
  - `SCHEMA` => `ProtectedDocument.SCHEMA`
  - `Class` => `ProtectedDocument`
- RDF [Removed]
- RDFRepresentation [Removed]
- Resource
  - `Class` => `Resource`
  - `Factory` => `Resource`
  - `Util` [Removed]
- SDKContext
  - `Class` => `SDKContext`
  - `interface` => globalContext
- ServiceAwareDocument
  - `Class` => `ServiceAwareDocument`
  - `Factory` => `ServiceAwareDocument`
- Settings
  - `PlatformPaths`
  - `DocumentPaths`
  - `ContextSettings`
  - `CarbonSettings`
  - [Reexport] (`Class`) [Removed]
- SPARQL [Removed]
- System [Removed]
- Utils
  - `O`     => `ObjectUtils`
  - `S`     => `StringUtils`
  - `A`     => `ArrayUtils`
  - `M`     => `MapUtils`
  - `UUID`  => `UUIDUtils`

## `carbonldp/Errors`

- AbstractError
  - `Class` => `AbstractError`
- IDAlreadyInUseError
  - `Class` => `IDAlreadyInUseError`
- IllegalActionError
  - `Class` => `IllegalActionError`
- IllegalArgumentError
  - `Class` => `IllegalArgumentError`
- IllegalStateError
  - `Class` => `IllegalStateError`
- InvalidJSONLDSyntaxError
  - `Class` => `InvalidJSONLDSyntaxError`
- NotImplementedError
  - `Class` => `NotImplementedError`

## `carbonldp/HTTP`

- Header
  - `Class` => `Header`
  - `Util` => `Header`
- JSONParser
  - `Class` => `JSOParser`
- Method
  - `Method` => `HTTPMethod`
- Parser
  - `Class` => `Parser`
- Request
  - `Options` => `RequestOptions`
  - `GETOptions`
  - `RetrievalPreferences`
  - `Service` => `RequestService`
  - `Util` => `RequestUtils`
- Response
  - `Class` => `Response`
  - `Utils` => `ResponseUtils`
- StatusCode
  - `StatusCode`
- StringParser
  - `Class` => `StringParser`

## `carbonldp/HTTP/Errors`

- `client` [Removed]
- `server` [Removed]
- `statusCodeMap`
- HTTPError
  - `Class` => `HTTPError`
- UnknownError
  - `Class` => `UnknownError`
- client => `ClientErrors`
  - BadRequestError
    - `Class` => `BadRequestError`
  - ConflictError
    - `Class` => `ConflictError`
  - ForbiddenError
    - `Class` => `ForbiddenError`
  - MethodNotAllowedError
    - `Class` => `MethodNotAllowedError`
  - NotAcceptableError
    - `Class` => `NotAcceptableError`
  - NotFoundError
    - `Class` => `NotFoundError`
  - PreconditionFailedError
    - `Class` => `PreconditionFailedError`
  - PreconditionRequiredError
    - `Class` => `PreconditionRequiredError`
  - RequestEntityTooLargeError
    - `Class` => `RequestEntityTooLargeError`
  - RequestHeaderFieldsTooLargeError
    - `Class` => `RequestHeaderFieldsTooLargeError`
  - RequestURITooLongError
    - `Class` => `RequestURITooLongError`
  - TooManyRequestsError
    - `Class` => `TooManyRequestsError`
  - UnauthorizedError
    - `Class` => `UnauthorizedError`
  - UnsupportedMediaTypeError
    - `Class` => `UnsupportedMediaTypeError`
- server `ServerErrors`
  - BadGatewayError
    - `Class` => `BadGatewayError`
  - BadResponseError
    - `Class` => `BadResponseError`
  - GatewayTimeoutError
    - `Class` => `GatewayTimeoutError`
  - HTTPVersionNotSupportedError
    - `Class` => `HTTPVersionNotSupportedError`
  - InternalServerErrorError
    - `Class` => `InternalServerErrorError`
  - NotImplementedError
    - `Class` => `NotImplementedError`
  - ServiceUnavailableError
    - `Class` => `ServiceUnavailableError`

## `carbonldp/JSONLD`

- Compacter
  - `Class` => `JSONLDCompacter`
- Converter
  - `Converter` => `JSONLDConverter`
- Parser
  - `Class` => `JSONLDParser`
- Processor
  - `Class` =>  `JSONLDProcessor`
- Utils => `JSONLDUtils`

## `carbonldp/LDP`

- AddMemberAction
  - `RDF_CLASS` => `AddMemberAction.TYPE`
  - `SCHEMA` => `AddMemberAction.SCHEMA`
  - `Class` => `AddMemberAction`
  - `Factory` => `AddMemberAction`
- DirectContainer
  - `RDF_CLASS` => `DirectContainer.TYPE`
  - `Class` => `DirectContainer`
  - `Factory` => `DirectContainer`
- DocumentMetadata
  - `RDF_CLASS` => `DocumentMetadata.TYPE`
  - `SCHEMA` => `DocumentMetadata.SCHEMA`
  - `Class` => `DocumentMetadata`
  - `Factory` => `DocumentMetadata`
- Entry
  - `SCHEMA` => `Entry.SCHEMA`
  - `Class` => `Entry`
- Error
  - `RDF_CLASS` => `Error.TYPE`
  - `SCHEMA` => `Error.SCHEMA`
  - `Class` => `Error`
- ErrorResponse
  - `RDF_CLASS` => `ErrorResponse.TYPE`
  - `SCHEMA` => `ErrorResponse.SCHEMA`
  - `Class` => `ErrorResponse`
  - `Util` => `ErrorResponse`
- Map
  - `RDF_CLASS` => `Map.TYPE`
  - `SCHEMA` => `Map.SCHEMA`
  - `Class` => `Map`
  - `Factory` => `Map`
- RemoveMemberAction
  - `RDF_CLASS` => `RemoveMemberAction.TYPE`
  - `SCHEMA` => `RemoveMemberAction.SCHEMA`
  - `Class` => `RemoveMemberAction`
  - `Factory` => `RemoveMemberAction`
- ResponseMetadata
  - `RDF_CLASS` => `ResponseMetadata.TYPE`
  - `SCHEMA` => `ResponseMetadata.SCHEMA`
  - `Class` => `ResponseMetadata`
  - `Factory` => `ResponseMetadata`
- ValidationError
  - `RDF_CLASS` => `ValidationError.TYPE`
  - `SCHEMA` => `ValidationError.SCHEMA`
  - `Class` => `ValidationError`
- VolatileResource
  - `RDF_CLASS` => `VolatileResource.TYPE`
  - `Class` => `VolatileResource`
  - `Factory` => `VolatileResource`

## `carbonldp/LDPatch`

- DeltaCreator
  - `Class` => `DeltaCreator`
- Tokens
  - `StatementToken`
  - `LDPatchToken`
  - `PrefixToken`
  - `TripleToken`
  - `AddToken`
  - `DeleteToken`
  - `UpdateListToken`
  - `SliceToken`

## `carbonldp/Messaging`

- AccessPointCreated
  - `RDF_CLASS` => `AccessPointCreated.TYPE`
  - `SCHEMA` =>  `AccessPointCreated.SCHEMA`
  - `Class` => `AccessPointCreated`
- ChildCreated
  - `RDF_CLASS` => `ChildCreated.TYPE`
  - `SCHEMA` => `ChildCreated.SCHEMA`
  - `Class` => `ChildCreated`
- Document
  - `Class` => `MessagingDocument`
  - `Factory` => `MessagingDocument`
- DocumentCreated
  - `SCHEMA` => `DocumentCreated.SCHEMA`
  - `Class` => `DocumentCreated`
- DocumentCreatedDetails
  - `RDF_CLASS` => `DocumentCreatedDetails.TYPE`
  - `SCHEMA` => `DocumentCreatedDetails.SCHEMA`
  - `Class` => `DocumentCreatedDetails`
- DocumentDeleted
  - `RDF_CLASS` => `DocumentDeleted.TYPE`
  - `SCHEMA` => `DocumentDeleted.SCHEMA`
  - `Class` => `DocumentDeleted`
- DocumentModified
  - `RDF_CLASS` => `DocumentModified.TYPE`
  - `SCHEMA` => `DocumentModified.SCHEMA`
  - `Class` => `DocumentModified`
- Event
  - `Event`
- MemberAdded
  - `RDF_CLASS` => `MemberAdded.TYPE`
  - `SCHEMA` => `MemberAdded.SCHEMA`
  - `Class` => `MemberAdded`
- MemberAddedDetails
  - `RDF_CLASS` => `MemberAddedDetails.TYPE`
  - `SCHEMA` => `MemberAddedDetails.SCHEMA`
  - `Class` => `MemberAddedDetails`
- MemberDetails
  - `SCHEMA` => `MemberDetails.SCHEMA`
  - `Class` => `MemberDetails`
- MemberRemoved
  - `RDF_CLASS` => `MemberRemoved.TYPE`
  - `SCHEMA` => `MemberRemoved.SCHEMA`
  - `Class` => `MemberRemoved`
- MemberRemovedDetails
  - `RDF_CLASS` => `MemberRemovedDetails.TYPE`
  - `SCHEMA` => `MemberRemovedDetails.SCHEMA`
  - `Class` => `MemberRemovedDetails`
- Message => `MessageEvent`
  - `RDF_CLASS` => `MessageEvent.TYPE`
  - `SCHEMA` => `MessageEvent.SCHEMA`
  - `Class` => `MessageEvent`
  - `Factory` => `MessageEvent`
- Options => `MessagingOptions`
  - `Options` => `MessagingOptions`
- Service => `MessagingService`
  - `DEFAULT_OPTIONS` [Not exported]
  - `Class` => `MessagingService`
- Utils => `MessagingUtils`

## `carbonldp/NS` => `carbonldp/Vocabularies`

- C
  - `namespace` => `C.namespace`
  - `Class` => `C.*`
  - `Predicate` => `C.*`
- CP [Removed]
- CS
  - `namespace` => `CS.namespace`
  - `Class` => `CS.*`
  - `Predicate` => `CS.*`
- LDP
  - `namespace` => `LDP.namespace`
  - `Class` => `LDP.*`
  - `Predicate` => `LDP.*`
- RDF
  - `namespace` => `RDF.namespace`
  - `Class` => `RDF.*`
  - `Predicate` => `RDF.*`
- SHACL
  - `namespace` => `SHACL.namespace`
  - `Class` => `SHACL.*`
  - `Predicate` => `SHACL.*`
- VCARD
  - `namespace` => `VCARD.namespace`
  - `Predicate` => `VCARD.*`
- XSD
  - `namespace` => `XSD.namespace`
  - `DataType` => `XSD.*`

## `carbonldp/RDF`

- Document
  - `Class` => `RDFDocument`
  - `Factory` => `RDFDocument`
  - `Util` => `RDFDocument`
  - `Parser` => `RDFDocumentParser`
- List
  - `Class` => `RDFList`
  - `Factory` => `RDFList`
- Literal
  - `Class` => `RDFLiteral`
  - `Factory` => `RDFLiteral`
- Node
  - `Class` => `RDFNode`
  - `Factory` => `RDFNode`
  - `Util` => `RDFNode`
- URI
  - `Class` => `URI` [Removed]
  - `Util` => `URI`
- Value
  - `Class` => `RDFValue`
  - `Util` => `RDFValue`

## `carbonldp/RDF/Literal`

- Serializer
  - `Class` => `RDFSerializer`
- Serializers [Removed]

## `carbonldp/RDF/Literal/Serializers`

- XSD
  - `DateSerializer`
  - `DateTimeSerializer`
  - `TimeSerializer`
  - `IntegerSerializer`
  - `LongSerializer`
  - `UnsignedIntegerSerializer`
  - `UnsignedLongSerializer`
  - `FloatSerializer`
  - `BooleanSerializer`
  - `StringSerializer`

## `carbonldp/SHACL`

- ValidationReport
  - `RDF_CLASS` => `ValidationReport.TYPE`
  - `SCHEMA` => `ValidationReport.SCHEMA`
  - `Class` => `ValidationReport`
- ValidationResult
  - `RDF_CLASS` => `ValidationResult.TYPE`
  - `SCHEMA` => `ValidationResult.SCHEMA`
  - `Class` => `ValidationResult`

## `carbonldp/SPARQL`

- Builder
  - `ExecuteSelect` => `FinishSPARQLSelect`
  - `Class` => `SPARQLBuilder`
- RAWResults
  - `ValuesTypes` [Removed]
  - `BindingObject` => `SPARQLRawBindingObject`
  - `BindingProperty` => `SPARQLRawBindingProperty`
  - `Class` => `SPARQLRawResults`
  - `Factory` => `SPARQLRawResults`
- RAWResultsParser
  - `Class` => `SPARQLRawResultsParser` [Removed]
- SELECTResults
  - `BindingObject` => `SPARQLBindingObject`
  - `Class` => `SPARQLSelectResults`
- Service
  - `Class` => `SPARQLService`

## `carbonldp/SPARQL/QueryDocument`

- PartialMetadata
  - `Class` => `PartialMetadata`
  - `ALL` => `PartialMetadata.ALL` [static value]
- QueryContext
  - `Class` => `QueryContext`
- QueryContextBuilder
  - `Class` => `QueryContextBuilder`
- QueryContextPartial
  - `Class` => `QueryContextPartial`
- QueryDocumentBuilder
  - `Class` => `QueryDocumentBuilder`
  - `ALL` => `QueryDocumentBuilder.ALL` [static value]
- QueryDocumentsBuilder
  - `Class` => `QueryDocumentsBuilder`
  - `OrderData` => `QueryDocumentsOrderData`
- QueryMetadata
  - `RDF_CLASS` => `QueryMetadata.TYPE`
  - `SCHEMA` => `QueryMetadata.SCHEMA`
  - `Class` => `QueryMetadata`
  - `Factory` => `QueryMetadata`
- QueryObject
  - `Class` => `QueryObject`
- QueryPropertiesSchema => `QuerySchema`
  - `Class` => `QuerySchema`
- QueryProperty
  - `PropertyType` => `QueryPropertyType`
  - `Class` => `QueryProperty`
- QueryPropertySchema => `QuerySchemaProperty`
  - `Class` => `QuerySchemaProperty`
- QueryValue
  - `Class` => `QueryValue`
- QueryVariable
  - `Class` => `QueryVariable`
- Utils => `QueryDocumentsUtils`

## `carbonldp/System`

- PlatformMetadata
  - `RDF_CLASS` => `PlatformMetadata.TYPE`
  - `SCHEMA` => `PlatformMetadata.SCHEMA`
  - `Class` => `PlatformMetadata`
