### ISSUE TITLE
Missing ConnectionHeaders and ExtendedHeaders

### ISSUE THREAD

**Issue by alvaro9210** [CarbonLDP/carbonldp-js-sdk#165]
When upgrading the SDK to `v1.0.0-alpha.4`, when bundling the transpiler launches the following error:
```bash
ERROR in [at-loader] ./node_modules/carbonldp/Messaging/Service.d.ts:7:26 
    TS2304: Cannot find name 'ConnectionHeaders'.

ERROR in [at-loader] ./node_modules/carbonldp/Messaging/Service.d.ts:12:18 
    TS2304: Cannot find name 'ExtendedHeaders'.
```

It seems those types are not being imported in the `d.ts` file.

**Comment by roddolf** [comment]
The `webstomp-client` library has incomplete typings.
And adding a workaround looks like TypeScript is removing this imported types thinking as unused imports.

A pull request has been made to the original library JSteunou/webstomp-client#54
