### ISSUE TITLE
Update README.md with reference to website user guide for JS SDK

### ISSUE THREAD

**Issue by codyburleson** [CarbonLDP/carbonldp-js-sdk#175]
You never know how users will land on information about Carbon LDP, so having handy cross-links in appropriate places would be beneficial. We should put links to the website user guide for the JS SDK in the README.md file. I'm thinking:

## JavaScript SDK User Guide

For information on how to use the SDK in your front-end development, please refer to the [JavaScript SDK user guide](https://carbonldp.com/documentation/v0.x.x/javascript-sdk/) on the Carbon LDP website.

(Although, I'm not sure if a section header is necessary.)

**Comment by roddolf** [comment]
@codyburleson 
The current README already has a link to the webpage documentation in the second paragraph.

Can the issue be considered done?

**Comment by codyburleson** [comment]
Can we also add a link to the JavaScript SDK API Reference? For example...

For information on how to use the SDK, please refer to the [JavaScript SDK user guide] and the [JavaScript SDK API Reference](https://carbonldp.github.io/carbonldp-js-sdk/).

**Comment by roddolf** [comment]
The page of the link "User Guide" already has the link to the API Reference.
And since it will change in a more equal documentation, would it be better to just link to the "main" documentation page as it is now?
