### ISSUE TITLE
The sdk not display error message when document types property is not an array

### ISSUE THREAD

**Issue by AlexSerrano22** [CarbonLDP/carbonldp-js-sdk#206]
when I tried to create a document, I had an error because I sent this object:
```
{
          "forecastID": "XXXX",
          "color": "green",
          "name": "CNH: CDFS Support 2016",
          "updatedDate": new Date("2016-10-31T16:26:15.101Z"),
          "types": "https://tms.base22.com/ns#ForecastProject"
        }
```
and the error is that types need to be an array, but the Issue that I report is related to the SDK, the SDK convert the object to a carbon document but this is not created on the platform because never send a request, but neither display an error message on the browser console.

**Comment by roddolf** [comment]
I have tested and it is working the promise rejection.

@AlexSerrano22 can you provide more information of what you are doing (code)?

**Comment by AlexSerrano22** [comment]
I think that we can close this issue because I had a recursive function and I forgot to include the catch at the end of the promise, I apologize :P
