### ISSUE TITLE
Query error when compacting referenced same level documents

### ISSUE THREAD

**Issue by roddolf** [CarbonLDP/carbonldp-js-sdk#211]
When retrieving all the children of a container that has references to the another children of the same container, the compacter can mistakenly treat them as subdocuments in a subquery.

Example: 
Documents in the form:
```json
{
  "@id": "users/1",
  "related-user": "users/2",
}
```

And applying the query:
```typescript
  documents.getChildren( "users/" )
```

Can throw the error related to the path `child.realted-user`

**Comment by roddolf** [comment]
@AlexSerrano22 @alex-arriaga can you check if installing `npm i github:carbonldp/carbonldp-js-sdk#next` solves your issue with the `getChildren` method?

**Comment by alex-arriaga** [comment]
Hi @roddolf this solved the issue; thank you. Please let us know when this is available in a alpha version of the SDK.
