### ISSUE TITLE
How can I order the related documents?

### ISSUE THREAD

**Issue by AlexSerrano22** [CarbonLDP/carbonldp-js-sdk#218]
hi guys I have a question: I'm working with getMembers to do a query to a document and his related documents like this:
```
carbon.documents.getMembers('/skills/',
          _ => _.withType(`${CarbonService.CONTEXT_URL}#Skill`).properties({
            '@id': _.inherit,
            'name': _.inherit,
            'skillLevels': {
              'query': _ => _
                .withType(`${CarbonService.CONTEXT_URL}#SkillLevel`)
                .properties({'name': _.inherit})
                **.orderBy( "name", "ascending" )**
            }
          })
```
because I want my skill levels to be orderly by his name. but I receive an error `properties(...).orderBy is not a function` but if I change the `.orderBy` to the first `.properties` this works, but how can I indicate that I want my skill levels to be orderly on this level e.g:

```
carbon.documents.getMembers('/skills/',
          _ => _.withType(`${CarbonService.CONTEXT_URL}#Skill`).properties({
            '@id': _.inherit,
            'name': _.inherit,
            'skillLevels': {
              'query': _ => _
                .withType(`${CarbonService.CONTEXT_URL}#SkillLevel`)
                .properties({'name': _.inherit})
            }
          }).orderBy("skillLevels", "ascending" ))

```

**Comment by alvaro9210** [comment]
You can always make use of dot notation to indicate to the `filter` and `orderBy` functions, the properties of the nested objects you want to use.
This means you can make use of `.orderBy("skillLevels.name", "ascending" ))` to sort by your nested object's `name` property.

**Comment by AlexSerrano22** [comment]
I add the answer on gitter

Rodolfo Aguirre @roddolf 13:35
@AlexSerrano22 As you have noticed, the order function is only available on the first level.
Sub-properties do not support orderBy, you would need to do it in the client.
