### ISSUE TITLE
Missing updateCredentials on PersistedUser Class

### ISSUE THREAD

**Issue by alvaro9210** [CarbonLDP/carbonldp-js-sdk#263]
On version `alpha.18` of the SDK, when trying to update a user's credential the SDK does not provide a method to easily do this.
Digging into the SDK's definitions files `.d.ts` I found out that there's such a way of doing that with the `updateCredentials` method, but it is only defined in the `User` type of object but not in the `PersistedUser` type.
This leaves me wondering, is this correct or is it just a missing method in the `PersistedUser` class.

![image](https://user-images.githubusercontent.com/4240006/39319220-1064f1fc-4946-11e8-81f7-ab6eed03b679.png)

![image](https://user-images.githubusercontent.com/4240006/39319213-07d11a2a-4946-11e8-9abc-564c08dcd56f.png)

Another question I had was... is this method going to execute a request to persist only the credentials?
That's what I understand when reading `updateSomething` if the intention is to just store the credential in the object and then persist this user object, then I think `setCredential` would be a more precise way to portrait the actions this method is going to do.

**Comment by roddolf** [comment]
With the changes in the security model, this method will be deleted in both models.
Changes applied at PR #256
