### ISSUE TITLE
CarbonLDP.Document not showing in main index in SDK docuemntation

### ISSUE THREAD

**Issue by codyburleson** [CarbonLDP/carbonldp-js-sdk#314]
Do I understand this correctly? Document is in the table of contents nav bar at left, but not in the main index at right (as shown in this image):

![image](https://user-images.githubusercontent.com/7317733/47055305-5fe82780-d17c-11e8-84f7-a148275aef4d.png)

**Comment by codyburleson** [comment]
The same is true also for `Context`

**Comment by roddolf** [comment]
The `carbonldp/Document` at the left menu is the module, and the main index shows the elements exported from all the modules.

But it looks the docs isn't rendering all the classes/interfaces of all the modules.
