### ISSUE TITLE
Retrieving nested documents is not working

### ISSUE THREAD

**Issue by mike-quiroga** [CarbonLDP/carbonldp-js-sdk#325]
When you are working WITHOUT a schema, and you are trying to retrieve properties of a nested document, using the property name, is not getting back the value.

```JavaScript
carbonldp.documents.$getChildren("process-centers/", function(_) {
                return _.properties({
                    "address": _.inherit,
                    "staffing": {
                        "query": function(_) { return _.properties({ "name": _.inherit }) }
                    }
                })
            })
```

**Comment by roddolf** [comment]
As a quick workaround for this case, you can set the `staffing` property as a Pointer:

```javascript
carbonldp.documents.$getChildren("process-centers/", function(_) {
    return _.properties({
        "address": _.inherit,
        "staffing": {
                "@type": "@id",
                "query": function(_) { return _.properties({ "name": _.inherit }) }
        }
    });
});
```

**Comment by codyburleson** [comment]
I thought use of `_.inherit` implies the use of a schema. As per documentation on [this page](https://carbonldp.com/documentation/v5.x.x/javascript-sdk/reading-documents/), 

"_.inherit specifies that the property’s details should be pulled from the Object schema."

So, I guess one question is - does it make sense to use `_.inherit` at all when not also using an Object schema? Here is a snippet from some code I used in the Carbon LDP / React blog tutorial, which does not use `_.inherit`, for example.

```
carbonldp.documents.$getMembers( "posts/", _ => _
          .properties( {
              "title": {
                  "@type": "string"
              },
              "slug": {
                  "@type": "string"
              },
              "excerpt": {
                  "@type": "string"
              }
          } )
      ).then(  (items) => {
              this.setState({items});
          }
      );
```

**Comment by mike-quiroga** [comment]
> I thought use of `_.inherit` implies the use of a schema. As per documentation on [this page](https://carbonldp.com/documentation/v5.x.x/javascript-sdk/reading-documents/),
> 
> "_.inherit specifies that the property’s details should be pulled from the Object schema."
> 
> So, I guess one question is - does it make sense to use `_.inherit` at all when not also using an Object schema? Here is a snippet from some code I used in the Carbon LDP / React blog tutorial, which does not use `_.inherit`, for example.
> 
> ```
> carbonldp.documents.$getMembers( "posts/", _ => _
>           .properties( {
>               "title": {
>                   "@type": "string"
>               },
>               "slug": {
>                   "@type": "string"
>               },
>               "excerpt": {
>                   "@type": "string"
>               }
>           } )
>       ).then(  (items) => {
>               this.setState({items});
>           }
>       );
> ```

```
 carbonldp.documents.$getChildren("process-centers/", function(_) {
                return _.properties({
                    "address": _.inherit,
                    "staffing": {
                        "query": function(_) {
                            return _.properties({
                                "name": {
                                    "@type": "string"
                                }
                            })
                        }
                    }
                })
            })
```
That either worked. _.inherit worked on the first level, but the @type does not work in query builder.
