### ISSUE TITLE
(Angular) ERROR Error: “StaticInjectorError(AppModule)

### ISSUE THREAD

**Issue by Yahaire** [CarbonLDP/carbonldp-js-sdk#328]
Using Angular 7, when declaring a variable that will contain a CarbonLDP object inside the parameters of the constructor of a component, this error is returned.

> ERROR Error: "StaticInjectorError(AppModule)[AppComponent -> CarbonLDP]: 
  StaticInjectorError(Platform: core)[AppComponent -> CarbonLDP]: 
    NullInjectorError: No provider for CarbonLDP!"

If you add the provider for CarbonLDP in the module that uses your component (Form example, app.module.ts), like
```
import { CarbonLDP } from 'carbonldp';

@NgModule({
  declarations: [...],
  imports: [...],
  providers: [
    CarbonLDP,
  ],
})
export class AppModule { }
```
the error becomes:
> Error: Can't resolve all parameters for CarbonLDP: (?).

I am guessing this is because Angular is trying to do something like trying to instantiate a CarbonLDP object, but CarbonLDP is expecting the route of the Carbon platform.

Am I doing something wrong?

**Comment by Yahaire** [comment]
A quick workaround I found for this is simply declaring and instantiating the variable outside the constructor  of my component like
```
carbon = new CarbonLDP("http://localhost:8083/");

constructor() { }
```
With this, declaring CarbonLDP as provider doesn't even seem to be needed.

This said, is this way of doing it correct?

**Comment by roddolf** [comment]
The SDK is framework agnostic.

To get working the constructor you need to specify an Angular provider.
See: https://angular.io/guide/dependency-injection-providers

An example would be:
```typescript
const carbonldp: CarbonLDP = new CarbonLDP("http://localhost:8083/");

@NgModule({
  providers: [{ provide: CarbonLDP, useValue: carbonldp }],
})
export class AppModule {}
```
