### ISSUE TITLE
Federated .$resolve() in Carbon

### ISSUE THREAD

**Issue by Yahaire** [CarbonLDP/carbonldp-js-sdk#344]
The property of one of my documents is a pointer to a node in a database different to Carbon's database: **Stardog**.

I'm trying to reference this Stardog database from its Carbon reference in order to make interaction with it more simple via using `$resolve()` on the property. Of course, since .$resolve() is meant to be used with Carbon documents, this resulted in the method not even existing when trying to call it, for example:
```
this.carbon.documents.$get(`movies/2af7e97d-58e3-43c8-ba9c-946e568e7a32/`)
    .then((movieDocument) => {
        return movie.movieResource.$resolve(); // Of course, this results in a 'not a function' error    
    })
    .then((movieNode) => {
        /* (Do stuff with the movie node from Stardog...) */
)};
```
Where my movieResource is found in
`https://movie-demo-ldp.carbonldp.com/vocabularies/main/#movieResource`

I understand a resolve here would translate into a federated query, and that it is not meant to be used, but I feel like it would be great if **_Carbon could have a way to make it easier for front-end developers to be able to get data from sources other than Carbon without having to resort to learning SPARQL as it is expensive to teach this language to your team_**.

Again, this could all be circumvented with a federated query such as:
```
// Consider the movie resource has already been obtained with Carbon's .$get and its value is
// "http://www.imdb.com/title/tt1322312"
CarbonLDP.SPARQL.SPARQLService.executeRawSELECTQuery('https://movie-demo-ldp.carbonldp.com/', `
            PREFIX : <http://schema.org/>
            PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

            SELECT *
            WHERE{ 
                SERVICE <db://demo> {
                    GRAPH <graph:imdb> {
                        <${movieResource}> ?relation ?value .
                    }
                }
            } 
            LIMIT 100
        `)
```
**but it would be so much more powerful to have something like the .$resolve() to do this same thing!** Personally, what I consider to be one of the best aspects of linked data is that it allows for data to be accessed even when you don't fully understand its structure, and it would probably be great if Carbon could make this easier to do with its SDK.

**Comment by roddolf** [comment]
It has been considered to add capabilities to the SDK to resolve external resources.

But it would be another feature different from the one you are suggesting.

Since the data you are trying to get is inside a closed Stardog database, where the URI (`http://www.imdb.com/title/tt1322312`) is not the real place where the resource data lives,
but this assumption the one that Linked Data requires and it is the base of the Platform/SDK.
