### ISSUE TITLE
Loosen the relationship between the exposed domain and the domain contained in the data

### ISSUE THREAD

**Issue by NormaCaballero** [CarbonLDP/carbonldp-js-sdk#425]
This task is related to platform update handled in https://github.com/CarbonLDP/carbonldp-platform.private/issues/307

**Comment by jumokee** [comment]
> Modify the SDK to support two URLs, one for the endpoint where the resources are being reached, and one for the domain contained in the data so that objects can be parsed. One of these properties will have to be optional and if it's not declared then that means the same URL needs to be used to call and parse resources.
