### ISSUE TITLE
Reference Blob definition, documentation in JS SDK Doc

### ISSUE THREAD

**Issue by codyburleson** [CarbonLDP/carbonldp-js-sdk#85]
Where we define documents.upload() with a method signature for a Blob, it could be helpful to have a note about what a Blob is and how to generate one. Perhaps just a "See also:" note pointing here:
https://developer.mozilla.org/en/docs/Web/API/Blob
Or...
For more information on 'Blob' and how to create one, see: https://developer.mozilla.org/en/docs/Web/API/Blob
Whatever you think is best. Perhaps just hyperlink the word "blob" in the method signature (if possible).

**Comment by MiguelAraCo** [comment]
Focus has shifted to the new version and this issue in particular won't be relevant anymore.
